# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(default=b'date', editable=False, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='EnumField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField()),
                ('type', models.CharField(default=b'enum', editable=False, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='NumberField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(default=b'number', editable=False, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[(b'text', b'text'), (b'number', b'number'), (b'date', b'date'), (b'enum', b'enum')], max_length=6)),
                ('field_choices', models.TextField(blank=True, help_text=b'If you are allowing the user to choose from preselected options via the enum type, please list the options here separated by a comma.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='insurance.Risk')),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('type', models.CharField(default=b'text', editable=False, max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='riskfield',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='insurance.RiskType'),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.RiskType'),
        ),
        migrations.AlterUniqueTogether(
            name='riskfield',
            unique_together=set([('risk_type', 'name')]),
        ),
    ]
