# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20180228_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='datefield',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insurance.RiskField'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enumfield',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insurance.RiskField'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numberfield',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insurance.RiskField'),
            preserve_default=False,
        ),
    ]
