# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20180228_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='field_choices',
            field=models.TextField(blank=True, default=b'', help_text=b'If you are allowing the user to choose from preselected options via the enum type, please list the options here separated by a comma.'),
        ),
    ]
