# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_auto_20180302_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefield',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='enumfield',
            name='choice',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='numberfield',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
