# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20180305_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enumfield',
            old_name='choice',
            new_name='enum',
        ),
    ]
